// Generated by CIRCT firtool-1.66.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module bitrevChisel(	// src/device/BitRev.scala:14:7
  input  io_sclk,	// src/device/BitRev.scala:17:14
         io_ss,	// src/device/BitRev.scala:17:14
         io_mosi,	// src/device/BitRev.scala:17:14
  output io_miso	// src/device/BitRev.scala:17:14
);

  reg       state;	// src/device/BitRev.scala:23:58
  reg [7:0] data;	// src/device/BitRev.scala:24:58
  reg [7:0] counter;	// src/device/BitRev.scala:25:58
  always @(posedge io_sclk or posedge io_ss) begin	// src/device/BitRev.scala:17:14
    if (io_ss) begin	// src/device/BitRev.scala:17:14
      state <= 1'h0;	// src/device/BitRev.scala:14:7, :23:58
      data <= 8'h0;	// src/device/BitRev.scala:24:58
      counter <= 8'h0;	// src/device/BitRev.scala:25:58
    end
    else begin	// src/device/BitRev.scala:17:14
      automatic logic _GEN;	// src/device/BitRev.scala:37:20
      _GEN = counter == 8'h7;	// src/device/BitRev.scala:25:58, :37:20
      state <= ~state & _GEN | state;	// src/device/BitRev.scala:23:58, :26:16, :35:17, :37:{20,29}, :38:15
      if (state) begin	// src/device/BitRev.scala:23:58
        data <= {1'h0, data[7:1]};	// src/device/BitRev.scala:14:7, :24:58, :31:{18,33}
        counter <= counter + 8'h1;	// src/device/BitRev.scala:25:58, :45:26
      end
      else begin	// src/device/BitRev.scala:23:58
        data <= {data[6:0], io_mosi};	// src/device/BitRev.scala:24:58, :28:{18,23}
        if (_GEN)	// src/device/BitRev.scala:37:20
          counter <= 8'h0;	// src/device/BitRev.scala:25:58
        else	// src/device/BitRev.scala:37:20
          counter <= counter + 8'h1;	// src/device/BitRev.scala:25:58, :41:28
      end
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/device/BitRev.scala:14:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/device/BitRev.scala:14:7
      `FIRRTL_BEFORE_INITIAL	// src/device/BitRev.scala:14:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/device/BitRev.scala:14:7
      automatic logic [31:0] _RANDOM[0:0];	// src/device/BitRev.scala:14:7
      `ifdef INIT_RANDOM_PROLOG_	// src/device/BitRev.scala:14:7
        `INIT_RANDOM_PROLOG_	// src/device/BitRev.scala:14:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/device/BitRev.scala:14:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/device/BitRev.scala:14:7
        state = _RANDOM[/*Zero width*/ 1'b0][0];	// src/device/BitRev.scala:14:7, :23:58
        data = _RANDOM[/*Zero width*/ 1'b0][8:1];	// src/device/BitRev.scala:14:7, :23:58, :24:58
        counter = _RANDOM[/*Zero width*/ 1'b0][16:9];	// src/device/BitRev.scala:14:7, :23:58, :25:58
      `endif // RANDOMIZE_REG_INIT
      if (io_ss) begin	// src/device/BitRev.scala:14:7
        state = 1'h0;	// src/device/BitRev.scala:14:7, :23:58
        data = 8'h0;	// src/device/BitRev.scala:24:58
        counter = 8'h0;	// src/device/BitRev.scala:25:58
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/device/BitRev.scala:14:7
      `FIRRTL_AFTER_INITIAL	// src/device/BitRev.scala:14:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_miso = ~(~io_ss & state) | data[0];	// src/device/BitRev.scala:14:7, :23:58, :24:58, :49:{17,18,32,59}
endmodule

